### ISSUE TITLE
Is Password policy and Virtual attribute creation required only one time at setup 

### ISSUE THREAD

**Issue by dsharmaCRWD** [pingidentity/ldapsdk#103]
Hi,

Is creating password policies and virtual attributes a one-time initial setup only task or do I need to keep doing this every time indexes are rebuilt or new records are added?

I'm using UnboundID version "5.0.0.0".
Commands used for creating password policies and virtual attribute:

- set-password-validator-prop
- create-password-validator
- create-password-policy
- create-virtual-attribute

**Comment by dirmgr** [comment]
It looks like you're trying to ask a question about the Ping Identity Directory Server (or maybe even an older version of the UnboundID Directory Server). This forum is only applicable to the UnboundID LDAP SDK for Java. In the future, please use the appropriate support channel for questions about server products.

But to answer your question (assuming that you are asking about the Ping or UnboundID server), then you shouldn't need to configure these items multiple times. Re-importing data and rebuilding indexes don't affect the configuration.

**Comment by dsharmaCRWD** [comment]
understood thank you.
