### ISSUE TITLE
Allow specifying a size limit on LDAP connection pool health checks

### ISSUE THREAD

**Issue by brucem-ping** [pingidentity/ldapsdk#107]
**Current behavior:**
When creating an object of type GetEntryLDAPConnectionPoolHealthCheck it is not possible to specify a size limit on the search it performs. 

In my case the LDAP server is set to close connections after a certain number of results. This causes the health check to always fail as the DN that the connection is checking will return more than the cut-off number of results and be closed.

**Desired behavior:**
I would like to be able to specify an optional size limit for my health check that is used for the search request creation here:
https://github.com/pingidentity/ldapsdk/blob/779c8b101c98e19c2d9bae578d2ba5fc8c2cc754/src/com/unboundid/ldap/sdk/GetEntryLDAPConnectionPoolHealthCheck.java#L244

ex:
```
public GetEntryLDAPConnectionPoolHealthCheck(@NotNull final String entryDN,
              final long maxResponseTime, 
              final long sizeLimit,
              final boolean invokeOnCreate,
              final boolean invokeAfterAuthentication,
              final boolean invokeOnCheckout, final boolean invokeOnRelease,
              final boolean invokeForBackgroundChecks,
              final boolean invokeOnException)
{
    // ...
    // general init here
    // ...
    searchRequest = new SearchRequest(this.entryDN, SearchScope.BASE,
         Filter.createPresenceFilter("objectClass"), "1.1");
    searchRequest.setResponseTimeoutMillis(this.maxResponseTime);
    if (sizeLimit != -1)
    {
        searchRequest.setSizeLimit(sizeLimit);
    }
}
```

**Comment by dirmgr** [comment]
The GetEntryLDAPConnectionPoolHealthCheck always issues its searches with a baseObject scope, which means that the only entry that can possibly match the search criteria is the one specified as the base DN. Unless the directory server that you're using is egregiously non-compliant, there's no way that the search could possibly return more than one entry.
