### ISSUE TITLE
search with ALL_OPERATIONAL_ATTRIBUTES doesn't return any operational attributes

### ISSUE THREAD

**Issue by gredwhite** [pingidentity/ldapsdk#153]
This code works and `token` is not null
```
val entry: SearchResultEntry = ldapConnectionPool.searchForEntry(baseDn, SearchScope.SUB, filter, SearchRequest.ALL_USER_ATTRIBUTES, "PrimaryGroupToken")
val token = entry.getAttributeValue("PrimaryGroupToken"))
```
   
 But if I execute this code    
   
   ```
val entry: SearchResultEntry = ldapConnectionPool.searchForEntry(baseDn, SearchScope.SUB, filter, SearchRequest.ALL_USER_ATTRIBUTES, SearchRequest.ALL_OPERATIONAL_ATTRIBUTES)
val token = entry.getAttributeValue("PrimaryGroupToken"))
```

 `token` is null with other parameters with the same values
 
 Actually  at this case I see the same amount of attributes as in the previous code snippet
 ```
 val entry: SearchResultEntry = ldapConnectionPool.searchForEntry(baseDn, SearchScope.SUB, filter, SearchRequest.ALL_USER_ATTRIBUTES)
 ```

**Comment by dirmgr** [comment]
I don't believe that Active Directory supports the use of the "+" token to indicate that all operational attributes should be retrieved. As per RFC 3673 (which defines that token), if it does, its root DSE should advertise a supportedFeatures value of "1.3.6.1.4.1.4203.1.5.1", so you can retrieve the root DSE to see if that feature OID is listed.

**Comment by gredwhite** [comment]
well... it is AD specific...again
