### ISSUE TITLE
Connections are not replaced if reconnect fails after connection reset

### ISSUE THREAD

**Issue by frankk3** [pingidentity/ldapsdk#28]
If a synchronous search request fails (_LDAPConnectionPool#search(...)_, _createIfNecessary_ is ‘false’) due to connection reset, _AbstractConnectionPool#replaceDefunctConnection()_ tries to replace the connection. But if this method also fails, neither a new connection is put into the pool (of course not), nor the connection pool's ‘failedReplaceCount’ is incremented.

This being the case, one connection is lost forever, and never replaced (also not by further search attempts).

Instead of that, the pool should remember that one connection has been closed (maybe with the help of its ‘failedReplaceCount’), and re-create it later on.

**Comment by dirmgr** [comment]
Thanks for reporting this, and for doing the detective work to track down the reason for it. I was able to write a test case to reproduce the bug, and I've just committed a fix for the problem (https://github.com/pingidentity/ldapsdk/commit/d1a0685d71bdf84da60397a9e350d40891400d62).

The fix will be included in the next release, but you can get it now if you check out and build the SDK for yourself.

**Comment by frankk3** [comment]
Wow, I'm impressed by your fast solution, many thanks for that. So I'm looking forward to the next release.

**Comment by frankk3** [comment]
As mentioned by @dirmgr and also documented in release notes https://docs.ldap.com/ldap-sdk/docs/release-notes.html, the fix is included in latest **unboundid-ldapsdk** release **version 4.0.0**, which is available since Jun 14th, 2017.

I was able to retest the fix successfully, i.e. my test scenario that  failed with version 3.2.1 (no connections in connection pool available after stopping and restarting openLDAP under load) worked fine with version 4.0.0.

So the issue is closed now.

Many thanks to @dirmgr for your fast solution, enhancing ldapsdk's robustness!
