### ISSUE TITLE
TLSv1.2 support for JDK8

### ISSUE THREAD

**Issue by chunghha** [pingidentity/ldapsdk#36]
Please support TLSv1.2 for JDK 8.

 ldapsdk/src/com/unboundid/util/ssl/SSLUtil.java 
 

> @param  protocol  The protocol to use.  As per the Java SE 6 Cryptography
>                       Architecture document, the set of supported protocols
>                       should include at least "SSLv3", "TLSv1", "TLSv1.1", and
>                       "SSLv2Hello".  It must not be {@code null}.

And, at least a note on document is needed to say SSLv3 protocol disabled by default with JDK 8.
https://docs.oracle.com/javase/8/docs/technotes/guides/security/enhancements-8.html
http://www.oracle.com/technetwork/java/javase/8u31-relnotes-2389094.html

**Comment by dirmgr** [comment]
The LDAP SDK does support TLSv1.2 on all supported Java versions, and it is enabled (and preferred) by default. Further, the LDAP SDK disables SSLv3 by default on all supported Java versions, regardless of whether it is enabled by default in the JVM. The documentation is out of date and will be updated to reflect that.

**Comment by chunghha** [comment]
@dirmgr thanks for the clarification.

**Comment by dirmgr** [comment]
I have just committed a change that updates the documentation. Thanks for pointing this out.
