### ISSUE TITLE
question: why does the InMemoryRequestHandler use ldifReader.readEntry()?

### ISSUE THREAD

**Issue by DemianTinkiel** [pingidentity/ldapsdk#61]
Hi,

I'm trying to use a `InMemoryDirectoryServer` and I see that its internal `InMemoryRequestHandler` uses `ldifReader.readEntry()` for its `importFromLDIF` operation.

The issue is that if I try to import an ldif with mixed content I get the exception
`
Caused by: LDIFException(lineNumber=1, mayContinueReading=true, message='The record starting at or near line number 1 contains a line that does not begin with an attribute name followed by a colon.', dataLines='dn: cn=schema ... {end-of-line}, ldapSDKVersion=4.0.4, revision=27051)
`

I was wondering if this could be related to https://github.com/pingidentity/ldapsdk/issues/1#issuecomment-113559569

**Comment by dirmgr** [comment]
The `importFromLDIF` method expects that the LDIF file contains only valid LDIF entries and not change records. That's the way that most LDAP server LDIF import processes work.

I can consider adding an `applyChangesFromLDIF` method, but for now if you've got a set of LDIF change records that you want to apply to the server, then you'll need to create your own LDIF reader, iterate through the change records, and apply them over an LDAP connection.

**Comment by DemianTinkiel** [comment]
Understood. Thanks for the clarification😁. I'll try your suggestion.

**Comment by dirmgr** [comment]
I have just committed a change that adds an `InMemoryDirectoryServer.applyChangesFromLDIF` method. It will be included in the next release of the LDAP SDK.

**Comment by DemianTinkiel** [comment]
That's great! Thanks!
