### ISSUE TITLE
How to exclude an attribute?

### ISSUE THREAD

**Issue by eddumelendez** [pingidentity/ldapsdk#70]
Currently, I am trying to exclude `userPassword` attribute. I found [this](https://stackoverflow.com/questions/52995864/removing-the-users-password-from-unboundid-ldap-search-results) in stackoverflow. There is another way to do that?

**Comment by dirmgr** [comment]
If you're asking about the LDAP SDK's in-memory directory server, then the best way to do that would be to use the InMemoryOperationInterceptor like is done for the linked example. The in-memory directory server is a very basic server primarily intended for testing purposes, and it doesn't implement any kind of access control mechanism.

If you're asking about LDAP in general, then this isn't really a standard feature. Some servers may implement this functionality, but the specific implementation would vary from one type of server to another. It would often be done through access control (and the way that you define access control rules also varies from one server to another), but some servers may have other features in this area (for example, the Ping Identity Directory Server has the ability to define sensitive attributes that offer stronger protections than just access control rules and can apply even to root users that might not be subject to access control evaluation).

**Comment by eddumelendez** [comment]
thanks @dirmgr. Yes, I am talking about in-memory directory server.
