### ISSUE TITLE
[Embedded LDAP] How to manually add an alias name to an attribute?

### ISSUE THREAD

**Issue by regenrek** [pingidentity/ldapsdk#80]
Hi,

I want to add alias names to the schema like for `street` -> `streetAddress` or `o` -> `organization`. How can I achieve this with embedded ldap server?

Regards

**Comment by dirmgr** [comment]
There are a couple of ways that you can do this.

One way would be to simply provide your own custom schema when creating the in-memory directory server instance. If you're using the in-memory-directory-server command line tool, you can use the `--useSchemaFile` argument to provide the path to an LDIF file that contains the schema definitions you want to use. If you're using it programmatically, you can use the `InMemoryDirectoryServerConfig.setSchema` method to provide the schema that you want to use. This is probably the best way if you want to use the same schema for a large number of tests.

Another option is to update the schema with the server online. You can do this with a regular LDAP modify operation, by manipulating the attributes used to specify the schema elements. For example, if you're using the default standard schema but want to update the definition for the street attribute type to add a streetAddress alias, you could apply a modification like:

```
dn: cn=schema
changetype: modify
delete: attributeTypes
attributeTypes: ( 2.5.4.9 NAME 'street' EQUALITY caseIgnoreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 X-ORIGIN 'RFC 4519' )
-
add: attributeTypes
attributeTypes: ( 2.5.4.9 NAME ( 'street' 'streetAddress' ) EQUALITY caseIgnoreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 X-ORIGIN 'RFC 4519' )
-
```

**Comment by regenrek** [comment]
Thank you for the useful info!
