### ISSUE TITLE
Need help on NTLM signing over LDAP authentication

### ISSUE THREAD

**Issue by MANOJ-SREERAMA** [pingidentity/ldapsdk#96]
I need to do NTLM authentication over LDAP protocol. For this I am trying to use LDAP SDK and jcifs-ng together. ([Courtesy](https://sourceforge.net/projects/javaldapntlmbind/)). Everything works fine using the code attached if domain controllers doesn't require LDAP signing (integrity check). If LDAP signing is enabled, code fails with message

> The server requires binds to turn on integrity checking if SSL\TLS are not already active on the connection

If I use NtlmFlags.NTLMSSP_NEGOTIATE_SIGN flag for Type3Message, code fails with following message ( even if LDAP Signing is disabled in domain controller )

> resultCode :: 49 (invalid credentials)
> resultCode :: 80090302: LdapErr: DSID-0C090588, comment: AcceptSecurityContext error, data 1, v2580

I have checked the working of GSSAPIBindRequest and DigestMD5BindRequest which supports authentication integrity over LDAP server. These implementations are using respective SASLClient mechanisms (GSSKbr5Client and DigestMD5Client) internally and these SASLClient implementations support auth-int (integrity check in authentication). I have tried using NTLMClient (SASLClient for NTLM)  but this implementation does not support authentication-integrity. So, no luck with that too. Please point me to any other way or the mistake in my approach. Thanks in advance.

Attached the code for reference.
[NtlmBindRequest.txt](https://github.com/pingidentity/ldapsdk/files/5499383/NtlmBindRequest.txt)

**Comment by dirmgr** [comment]
The LDAP SDK doesn't provide any direct support for NTLM authentication, and it looks like you're using a separate library for that. The SourceForge summary page for that library says, "Currently NTLM BIND authentication is implemented, but no NTLM signing or encryption of the connection is done." So it looks like a limitation of the library and not something that is directly part of the LDAP SDK.

The next release of the LDAP SDK will include some changes to make it easier for third-party SASL mechanisms to enable SASL integrity or confidentiality for communication (see #95), so maybe that will make it possible for the developer of the library you're using to add this support. But it's something that will ultimately need to be included in that library.

**Comment by MANOJ-SREERAMA** [comment]
Thanks for the reply!! :)
